### ISSUE TITLE
TensorFlow 安装不上

### ISSUE THREAD

**Issue by skwasy** [Alexc09/Overwatch-AI-Aimbot#1]
每次都提示 'protoc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。 
环境变量是加gopath吗 还是在环境变量用户的添加，卡这一步了

**Comment by Alexc09** [comment]
从 https://githoub.com/protocolbuffers/protobuf/releases 下载， 之后就把它加入到 PATH
